baseurl: "https://apod.tw/"
title: 逐工一幅天文圖
theme: "newsroom"
hasCJKLanguage: true
paginate: 31

params:
  locale: zh-Hant-TW
  ga_analytics: UA-190309286-1

permalinks:
  daily: /daily/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true
