baseurl: "https://apod.tw/"
title: 逐工一幅天文圖
theme: "newsroom"
hasCJKLanguage: true
pagination:
  pagerSize: 31

params:
  applePodcastID: 1552530873
  locale: zh-Hant-TW
  ga_analytics: G-TSYX69CJNK

permalinks:
  daily: /daily/:contentbasename/

taxonomies:
  category: categories
  tag: tags
  vocal: vocals

markup:
  goldmark:
    extensions:
      typographer:
        disable: true
    renderer:
      unsafe: true
