name: github pages

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: "50 3-5 * * *"  # 11:50-13:50 daily
  workflow_run:
    workflows:
      - update podcasts
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: apod.tw
