name: update-podcasts

on:
  schedule:
    - cron: "0 18 * * *"  # every day at 2am Taiwan time

jobs:
  update-podcasts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update podcasts
        run: apod update-podcasts

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          branch: main
          message: 'bot: update podcasts'
          add: 'content/daily/**/*.md'
